### ISSUE TITLE
Trocar banner do http://sites.bvsalud.org/factores-de-riesgo para retirar o logo do REGULA

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/leisref-wp-plugin#12]

**Comment by viniciusandrade** [comment]
Ajuste realizado pelo admin do WP.

**Comment by renatomurasaki** [comment]
@marcoslmori @viniciusandrade 

O logo do Regula voltou no banner. Creio que foi na transição das urls.

**Comment by viniciusandrade** [comment]
@renatomurasaki 
Atualizei novamente os banners na instância.
