### ISSUE TITLE
Falta de tradução na etiqueta dos clusters no idioma português e inglês

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/leisref-wp-plugin#15]
Isso acontece somente em http://sites.bvsalud.org/legislacion/pt/factores-de-riesgo. No site original http://sites.bvsalud.org/factores-de-riesgo/pt/legislacion está correto.

Idem para a versão inglês.

**Comment by viniciusandrade** [comment]
Feita a cópia dos arquivos de tradução da instância anterior para a nova.
