### ISSUE TITLE
Erro na visualização dos clusters Pais e Tipo de Ato nos idiomas português e inglês

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/leisref-wp-plugin#16]
![image](https://user-images.githubusercontent.com/1226218/44751057-862f0680-aaed-11e8-8c40-21e6d35237b6.png)

**Comment by viniciusandrade** [comment]
@renatomurasaki 

Adicionei as traduções da lista controlada de "País do Ato" mas é necessário a tradução da lista controlada de "Tipo de Ato"  para a correta apresentação nos idiomas deste filtro.

Favor informar quando estiver disponível para que seja feito a re-indexação dos atos.

[]s

**Comment by renatomurasaki** [comment]
@viniciusandrade traduções atualizadas. Apenas Resolución Ministerial (*) estava duplicado.

**Comment by viniciusandrade** [comment]
@renatomurasaki 
OK. Índice atualizado e termo duplicado removido da lista de controle.
