### ISSUE TITLE
Criar nova opção de página inicial do plug-in

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/leisref-wp-plugin#17]
Fazer com que o plug-in permita que o web master defina a arquitetura da página inicial:

1) Usar a página atual (lista dos atos normativos + clusters)
2) Usar página com um mosaico de cards (clusters)

**Comment by viniciusandrade** [comment]
@cordeirofilho 

Criar protótipo HTML com o novo formato de página inicial levando-se em consideração o site http://sites.bvsalud.org/legislacion/factores-de-riesgo/

**Comment by cordeirofilho** [comment]
segue uma tela de prototipo para o layout

![](https://user-images.githubusercontent.com/460341/45118440-ea297e80-b12e-11e8-80a3-3a0f1fd8647f.png)

**Comment by renatomurasaki** [comment]
@cordeirofilho proposta de layout aprovada pela equipe de LEG e NMH na Sede da OPAS/OMS. Pode seguir com a implementação, por favor.

**Comment by viniciusandrade** [comment]
Ajuste incorporado no plugin.
