### ISSUE TITLE
Ajustar a nova página inicial para visualização mobile

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/leisref-wp-plugin#24]
Ajustes:

- [ ] banner quebrado
- [ ] manter a mesma ordem dos clusters na visualização desktop
- [ ] alguns totais estão se sobrepondo ao label da opção de filtro

**Comment by wilsonmoura** [comment]
Exemplo: https://sites.teste.bvsalud.org/legislacion

**Comment by marcioalvessilva** [comment]
@wilsonmoura inserir esse CSS no final style.css 

@media (max-width:1000px){
	UL.col3 LI{
		WIDTH: 27%!important;
	}
}
@media (max-width:992px){
	UL.col3 LI{
		WIDTH: 41%!important;
	}
}
@media (max-width:600px){
	UL.col3 LI{
		WIDTH: 80%!important;
	}
}
