### ISSUE TITLE
Erro na visualição de cidade do ato

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/leisref-wp-plugin#28]
http://sites.bvsalud.org/legislacion/factores-de-riesgo/resource/?id=leisref.act.2077

O label "Esfera del acto" não resolve o idioma do nome da cidade: Municipal - pt-br^Bahía Blanca|en^Bahía Blanca|es^Bahía Blanca

**Comment by viniciusandrade** [comment]
Corrigido em https://github.com/bireme/leisref-wp-plugin/commit/ddc1e81ed2b1fec3b08f15705fb5b5645291a04f
