### ISSUE TITLE
Não está aparecendo o label do tipo de relacionamento entre os atos

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/leisref-wp-plugin#29]
Desapareceu o label que identifica o tipo de relacionamento entre os atos, tanto no resultado de busca, como no detalhamento do ato. Aparece apenas a referência para o ato que está relacionado.

Exemplos: http://sites.bvsalud.org/legislacion/pt/factores-de-riesgo?filter=scope_region:%22es^Peru|pt-br^Per%C3%BA|en^Peru%22

**Comment by viniciusandrade** [comment]
Decorrente de um conflito entre o código do plugin de legislação e de registros bibliográficos que utilizam a mesma função para tratar a apresentação deste campo. Já resolvido.
