### ISSUE TITLE
Incluir na chamada do serviço de similares as palavras da indexação DeCS/MeSH

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/leisref-wp-plugin#30]
As palavras do DeCS/MeSH são mais relevantes da descrição daquilo que realmente o ato normativo representa, uma vez que nem sempre há ementa e a ementa não oficial pode não ser tão representativa.

@viniciusandrade o @heitorbarbieri também alterou o algoritmo para incluir mais n-grams na busca, porém para legislação é fundamental a inclusão das palavras DeCS/MeSH

**Comment by viniciusandrade** [comment]
Implementado.
O parâmetro de busca que é passado para o serviço de similares agora é composto pelos seguintes campos da lei:
- título da lei
- lista de descritores
- ementa oficial / ementa não-oficial
