### ISSUE TITLE
Corrigir visualização da informação do ato normativo relacionado, qdo o mesmo não tem número e/ou data de publicação

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/leisref-wp-plugin#32]
Exemplos:

http://sites.bvsalud.org/legislacion/factores-de-riesgo/resource/?id=leisref.act.2365

Alterar de "Modifica Ley s/n, de 01 de Septiembre de 1969 - section 2" para "Modifica Ley Health Services Act, Chapter 44, de 01 de Septiembre de 1969"

http://sites.bvsalud.org/legislacion/factores-de-riesgo/resource/?id=leisref.act.2316

Alterar de "Fue modificada por Ley s/n, de //None" para "Fue modificada por Ley Health Services (Amendment) Act".

Regra geral: quando não tem número, colocar o Título. Quando não tem data de publicação, deixar apenas o tipo e número ou título.

**Comment by viniciusandrade** [comment]
Template revisado em https://github.com/bireme/leisref-wp-plugin/commit/4b5696018deff273594ea25d226c7d061b2248ae
