### ISSUE TITLE
Desarrollar scripts web que simulen los enlaces de TC-Legis en la nueva plataforma, mitigando el riesgo de enlaces rotos

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/leisref-wp-plugin#41]

**Comment by viniciusandrade** [comment]
Scripts iniciais desenvolvidos para redirecionamento dos seguintes casos de URL:

http://test.e-legis-ar.msal.gov.ar/leisref/public/showAct.php?id=20077

http://test.e-legis-ar.msal.gov.ar/leisref/public/search.php?type=decreto/(5)&number=1313&day=24&month=06&year=1993

Scripts de redirecionamento correspondentes:

https://legis-ar.msal.teste.bvsalud.org/redirect/showAct.php?id=20077

https://legis-ar.msal.teste.bvsalud.org/redirect/search.php?type=decreto/(5)&number=1313&day=24&month=06&year=1993

** Este issue será reaberto se forem identificados novos casos que necessitem redirecionamento.
