### ISSUE TITLE
Realizar capacitación en línea para el uso de FI-Admin en la gestión y publicación de LEGISALUD

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/leisref-wp-plugin#43]

**Comment by anakatiacamilo** [comment]
@viniciusandrade, Estamos fazendo a documentação e as apresentações para a capacitação e precisamos da documentação das permissões dos perfis (documentalista, editor e administrador). 

O Curso foi agendado para quinta-feira da semana que vem dia 18/02,
Grata

**Comment by viniciusandrade** [comment]
@anakatiacamilo atualizei a página de documentação de permissões levando em consideração o código do sistema:

https://github.com/bireme/fi-admin/wiki/Permiss%C3%B5es

Não adicionei o perfil administrador pois as listas controladas do módulo de legislação só estão disponíveis para usuários  internos da BIREME (perfil superuser).

**Comment by anakatiacamilo** [comment]
@viniciusandrade Obrigada

**Comment by anakatiacamilo** [comment]
Capacitação Realizada dia 18/02/2021 dás 15h às 16h30 com o apoio da Equipe FI e o Mori.
Participantes:
Adriana Calveiro
Ana Kátia Camilo
Angélica de Paula
Flavio Hazrum
Lais Aparecida da Silva
Laura Acosta
Marcos L. Mori
Oscar Baggini
Oscar Garay 
Sueli Mitiko Yano Suga
