### ISSUE TITLE
Realizar capacitación en línea para el uso del plug-in WordPress responsable por el sitio web de consulta de LEGISALUD

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/leisref-wp-plugin#44]

**Comment by renatomurasaki** [comment]
@marcoslmori esta capacitación ya fue realizada?

**Comment by marcoslmori** [comment]
Essa capacitação será realizado após a instalação da instancia de WP no servidor da Argentina.  Conjuntamente a essa capacitação de configuração do plugin , será também instruído a forma de customizar de acordo com a necessidade da contraparte.

**Comment by marcoslmori** [comment]
capacitação finalizada e enviado o link do vídeo para a contraparte
