### ISSUE TITLE
Probar y ajustar las funcionalidades del nuevo sitio web de consulta a LEGISALUD

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/leisref-wp-plugin#45]

**Comment by renatomurasaki** [comment]
@viniciusandrade esta actividad ya fue realizada o aún esperamos confirmación?

**Comment by viniciusandrade** [comment]
@renatomurasaki esperamos confirmación despues de la instalación del plugin en ambiente de producción final.

**Comment by viniciusandrade** [comment]
Ajustes finais solicitados (07/04)

- Criterio / orden de visualización / presentación de metadatos de normas recuperadas. Sort sin configuración. Opción propuesta: por campo fecha de publicación, orden decreciente (de más nueva a más vieja)

- Botón Opción para ejecutar nueva búsqueda luego de visualizar metadatos de búsqueda previa.

- Búsqueda por defecto por palabras de textos completos de archivos pdf.

**Comment by viniciusandrade** [comment]
Ajuste realizado em https://github.com/bireme/db-processing/issues/403 para extração dos conteúdos dos arquivos PDFs e inclusão no índice de busca do plugin do campo **content**.

**Comment by viniciusandrade** [comment]
Ajustes no plugin realizados e apresentados ao Oscar em reunião de 12/04.
