### ISSUE TITLE
Criar ambiente de homologação em ambiente da BIREME

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/leisref-wp-plugin#46]

**Comment by marcoslmori** [comment]
instancia de wordpress instaladas com os plugins necessários

https://legis-ar.msal.teste.bvsalud.org/l

**Comment by marcoslmori** [comment]
informações de servidor e path, foi enviada para os desenvolvedores por email

**Comment by marcoslmori** [comment]
instalado os plugins

Akismet Anti-Spam (configurado)
bvs
Classic Editor
Contact Form 7
Google Analytics for WordPress by MonsterInsights (sem id do google analytics - instancia não ficará na BIREME)
iThemes Security 
LeisRef
Page Links to
Polylang - Configurado apenas para o espanhol
WP Mail SMTP (não configurado instancia  - não ficará na BIREME)

Tema 2012 do plugin da BVS
