### ISSUE TITLE
Nova guia é fechada automaticamente quando clica no Link para documento em servidor de ftp no navegador chrome 

### ISSUE THREAD

**Issue by marcoslmori** [bireme/leisref-wp-plugin#47]
link para servidor ftp:
Exemplo: https://ses.sp.bvs.br/leisref/resource/?id=leisref.act.5475

Comportamento normal:
https://ses.sp.bvs.br/leisref/resource/?id=leisref.act.5565  link para documento em servidor https

Nos navegadores firefox e IE funciona normalmente

**Comment by wilsonmoura** [comment]
@marcoslmori esse problema ainda persiste? Favor confirmar se essa demanda ainda é necessária.

**Comment by marcoslmori** [comment]
Testado chrome e funciona corretamente
