### ISSUE TITLE
Nuevos filtros en el plugin en el sitio LEGISALUD

### ISSUE THREAD

**Issue by marcoslmori** [bireme/leisref-wp-plugin#48]
Columna derecha Filtros de búsqueda:
•	Agregar: Jurisdicción del acto
•	Agregar; Alcance del acto

Informado por Oscar

Issue relacionado: #40

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/leisref-wp-plugin/commit/e4b4827bc3cd1e3b11bde8ba20082b02ed76ca21
