### ISSUE TITLE
Etiqueta duplicada en la visualización  de presentación del sitio de LEGISALUD

### ISSUE THREAD

**Issue by marcoslmori** [bireme/leisref-wp-plugin#51]
La etiqueta Esfera del acto se visualiza por duplicado cuando se accede a vea más

Issue relacionado: #40

**Comment by viniciusandrade** [comment]
Corrigido em https://github.com/bireme/leisref-wp-plugin/commit/b32231bc14e912e373e602537531f404851fa491
