### ISSUE TITLE
Las etiquetas "Deroga" y "Fue derogado por" estan al revés en Sitio LEGISALUD

### ISSUE THREAD

**Issue by marcoslmori** [bireme/leisref-wp-plugin#52]
Las etiquetas "Deroga" y "Fue derogado por" estan al revés, es decir, deben intercambiarse donde dice "Deroga" debe decir "Fue derogado por" y donde dice 
"Fue derogado por" debe decir "Deroga

Issue relacionado: #40

**Comment by viniciusandrade** [comment]
@anakatiacamilo podemos verificar em conjunto esta observação do Oscar? 

Peguei um exemplo e me parece que no plugin esta refletindo corretamente a entrada de dados, por isso gostaria de verifcar se pode haver algum ajuste necessário na importação.

Exemplo:
![legis-deroga-1](https://user-images.githubusercontent.com/349287/106912190-8df12d00-66e1-11eb-9b1b-43cc911cf728.png)
![legis-deroga-11](https://user-images.githubusercontent.com/349287/106912198-90538700-66e1-11eb-86b3-d713fe80d666.png)
![legis-deroga-2](https://user-images.githubusercontent.com/349287/106912212-934e7780-66e1-11eb-8dc3-55dde07f9c13.png)
![legis-deroga-22](https://user-images.githubusercontent.com/349287/106912219-95b0d180-66e1-11eb-89b6-e278e92e0f89.png)

**Comment by anakatiacamilo** [comment]
@viniciusandrade, pelo que verifiquei a migração deste registros do exemplo estão corretos, vou marcar uma reunião com o Oscar para conversar sobre este issue para ver se os lables do FI-ADMIN também estão com problema.

**Comment by viniciusandrade** [comment]
@anakatiacamilo, obrigado pela verificação ... por favor quando tiver mais informação sobre este item adicione aqui para acompanharmos.

**Comment by anakatiacamilo** [comment]
@viniciusandrade, conforme reunião com o Oscar realmente era problema de migração. Vou fazer ajustes e refazer a migração.

**Comment by viniciusandrade** [comment]
OK, obrigado e qualquer dúvida entre em contato.
