### ISSUE TITLE
Realizar nova exportação do WP do LEGISALUD Argentina devido a alteração de domínio

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/leisref-wp-plugin#55]
Confirmado pelo Oscar em 16/04 que o domínio que será utilizado para o projeto é o: **e-legis-ar.msal.gov.ar**

Enviar novos arquivos de exportação para o Oscar realizar instalação no servidor do projeto.

**Comment by marcoslmori** [comment]
Atividade efetuada e já validada pelo Oscar

**Comment by viniciusandrade** [comment]
Obrigado Mori
