### ISSUE TITLE
Erro na recuperação de registros

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/leisref-wp-plugin#57]
De: ctd <ctd@saude.sp.gov.br>
Enviado: quarta-feira, 27 de outubro de 2021 12:15
Assunto: Base de Dados LEGSES - BVS RIC - Problemas na recuperação da informação
 
Angélica, tudo bem?

Tenho observado algumas situações estranhas na recuperação de pesquisa na base de dados LEGSES.
Cito abaixo alguns exemplos:

Ao pesquisar o Decreto nº 61.981, o sistema traz 2 resultados que não condizem com o número pesquisado.

![image](https://user-images.githubusercontent.com/47643830/139674923-f73e327f-bf37-4cd1-b382-5e1c37c54e4a.png)

Outra situação, ao pesquisar o número de um decreto o resultado é uma Deliberação

![image](https://user-images.githubusercontent.com/47643830/139674948-5b00aaf2-3dde-480b-8585-3aefdb21d6ad.png)

Podem, por favor verificar o que está acontecendo?
Seria algum erro de preenchimento ou de direcionamento do sistema???

Estes problemas podem confundir os usuários e impactar na credibilidade da base de dados.

Agradecemos a atenção e ficamos no aguardo de orientações.

Atenciosamente,

Lilian N. Schiavon
Coordenação da BVS Rede de Informação e Conhecimento
CCTIES/SES-SP

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula favor informar a usuária que para o sistema de busca de legislação também estamos recuperando o texto completo da lei, onde nestes dois casos citados a lei 61.981 se encontra dentro do PDF do texto da lei.

Obrigado
