### ISSUE TITLE
Criar cluster de Indexado em

### ISSUE THREAD

**Issue by suelisuga** [bireme/leisref-wp-plugin#58]
Solicito criar cluster utilizando o campo Indexado em.

Por enquanto não há nome para o cluster, irei consultar contraparte, mas Base de dados ou Coleção me parece bom visto que são de assuntos e países.

Muito obrigada!

**Comment by viniciusandrade** [comment]
@wilsonmoura verifiquei que o cluster **indexed_database** já esta disponível e populado com os dados dos registros de legislação ... acredito que seja somente ajuste no plugin para mostrar o filtro.

**Comment by wilsonmoura** [comment]
@suelisuga o filtro "Base de Dados" foi implementado conforme solicitado. Favor validar.
