### ISSUE TITLE
Formato de saída não aparece o link para o texto completo (Repositório de Legislação instancia de teste)

### ISSUE THREAD

**Issue by marcoslmori** [bireme/leisref-wp-plugin#59]
Instancia:  https://sites.teste.bvsalud.org/legislacion/ 
Wordpress multisite versão 5.9 funciona con el tema [BVS 2012]

![image](https://user-images.githubusercontent.com/10047460/170360893-bc01d31b-324c-4a8f-80ea-95c2235a5322.png)

No entanto na produção o link de texto completo funciona corretamente: 
https://sites.bvsalud.org/legislacion/factores-de-riesgo/
4.8.2 funciona con el tema [BVS 2012]

![image](https://user-images.githubusercontent.com/10047460/170361067-2625d4c3-8dd6-42ba-b556-9577828f711e.png)

**Comment by viniciusandrade** [comment]
@marcoslmori código do plugin revisado e atualizado em ambiente de testes. 

Favor, quando possível validar.

Obrigado

**Comment by marcoslmori** [comment]
OK

**Comment by marcoslmori** [comment]
@vini, links para o texto completo funcionando ok,  Obrigado

**Comment by viniciusandrade** [comment]
OK, obrigado pela validação
