### ISSUE TITLE
compatibilizar o plugin com o php 8

### ISSUE THREAD

**Issue by marcoslmori** [bireme/leisref-wp-plugin#63]
Identificado o erro na instancia da cns.bvs.br/leisref

Erro
-------------------------------------------------------
Fatal error: Uncaught DivisionByZeroError: Division by zero in /home/apps/bvs.br/wp-cns/htdocs/wp-content/plugins/leisref/lib/Paginator.php:22 Stack trace: #0 /home/apps/bvs.br/wp-cns/htdocs/wp-content/plugins/leisref/template/home.php(109): Paginator->paginate() #1 /home/apps/bvs.br/wp-cns/htdocs/wp-content/plugins/leisref/leisref.php(144): include('...') #2 /home/apps/bvs.br/wp-cns/htdocs/wp-includes/class-wp-hook.php(308): LeisRef_Plugin->theme_redirect() #3 /home/apps/bvs.br/wp-cns/htdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters() #4 /home/apps/bvs.br/wp-cns/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action() #5 /home/apps/bvs.br/wp-cns/htdocs/wp-includes/template-loader.php(13): do_action() #6 /home/apps/bvs.br/wp-cns/htdocs/wp-blog-header.php(19): require_once('...') #7 /home/apps/bvs.br/wp-cns/htdocs/index.php(17): require('...') #8 {main} thrown in /home/apps/bvs.br/wp-cns/htdocs/wp-content/plugins/leisref/lib/Paginator.php on line 22

**Comment by wilsonmoura** [comment]
@marcoslmori ajustes realizados. Favor atualizar o plugin e testar.

**Comment by marcoslmori** [comment]
Atualizado em produção e funcionando corretamente https://cns.bvs.br/leisref
